version: '3'
services:
  mysshd:
    image: calife/test:mysshd
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
     - "2222:22" 
    networks:
      - sshnet
networks:
  sshnet:
